#pragma once

enum {
    ERROR_OK =0,
    ERROR_THREAD_STARTED = 101,
    ERROR_THREAD_DISPOSED = 102,
    ERROR_ST_CREATE_CYCLE_THREAD = 103,
    ERROR_THREAD_INTERRUPED = 104,
    ERROR_THREAD_TERMINATED = 105,
    ERROR_INNER = 500
};